AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  LambdaCodeVersion:
    Type: String
    Description: Version of code used in the lambda.
Resources:
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AWSLambdaExecute"
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      RoleName: lambda-role
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:**963,
  InternshipCheckerLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda for checking internships on company career sites
      Code:
        S3Bucket: radswn-lambda-bucket
        S3Key: function.zip
        S3ObjectVersion: !Ref LambdaCodeVersion
      Handler: check
      Timeout: 10
      Runtime: go1.x
      Role: !GetAtt LambdaFunctionRole.Arn
  InternshipTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "Id"
          KeyType: "HASH"
      BillingMode: "PROVISIONED"
      ProvisionedThroughput:
        ReadCapacityUnits: 50
        WriteCapacityUnits: 5
Outputs:
  LambdaRoleARN:
    Description: Arn for lambda role
    Value:
      Fn::GetAtt:
      - LambdaFunctionRole
      - Arn
    Export:
      Name: lambda-role