AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  CodeBucketName:
    Type: String
    Description: The name of the bucket with Lambdas' code
  CheckerLambdaCodeVersion:
    Type: String
    Description: Version of code used in the checker lambda
  CheckerLambdaZip:
    Type: String
    Description: Name of .zip with checker lambda code
Resources:
  CheckerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AWSLambdaExecute"
      - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
  CheckerLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda for checking internships on company career sites
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref CheckerLambdaZip
        S3ObjectVersion: !Ref CheckerLambdaCodeVersion
      Handler: checker
      Timeout: 15
      Runtime: go1.x
      Role: !GetAtt CheckerLambdaRole.Arn

Outputs:
  CheckerLambdaRoleARN:
    Description: Arn for lambda role
    Value:
      Fn::GetAtt:
      - CheckerLambdaRole
      - Arn
    Export:
      Name: lambda-role